baseURL = "https://gavinelder.dev/"
languageCode = "en-us"
title = "Random Musings "
theme = "m10c"
publishDir = "docs"

[params]
  author = "Gavin Elder"
  description = "Random items"
[[params.social]]
  icon = "github"
  name = "github"
  url = "https://github.com/gavinelder"
[[params.social]]
  icon = "twitter"
  name = "twitter"
  url = "https://twitter.com/gavelder"
