baseURL = "https://gavinelder.dev/"
languageCode = "en-us"
title = "Random Musings"
theme = "m10c"
publishDir = "docs"

[params]
  author = "Gavin Elder"
  description = "Security Engineer, Ops enthusiast, Scottish."
  #avatar = "images/avatar.jpg"

[[params.social]]
  icon = "github"
  name = "github"
  url = "https://github.com/gavinelder"
[[params.social]]
  icon = "twitter"
  name = "twitter"
  url = "https://twitter.com/gavelder"
[[params.social]]
  icon = "linkedin"
  name = "linkedin"
  url = "https://www.linkedin.com/in/gavinelder/"
